### ISSUE TITLE
Dotnet core version

### ISSUE THREAD

**Issue by tasgray** [hitmanpt/whmcs-api#14]
Hey Pedro, great wrapper thank you so much! A dotnet core version would be awesome too.

**Comment by PedroCavaleiro** [comment]
Glad you like it, as soon as I get some free time I get on it

**Comment by PedroCavaleiro** [comment]
I just published the .NET Core version, did not added any new functionality, but feel free to submit the models that you need.

[Release 0.8.13](https://github.com/PedroCavaleiro/whmcs-api/releases/tag/0.8.13)
